[package]
name = "aion-event-executable"
version = "0.1.0"
edition = "2024"

[dependencies]
aion-event = { path = "../../aion-event" }
aion-program = { path = "../../aion-program" }
aion-processor = { path = "../../aion-processor" }
aion-ecs = { path = "../../aion-ecs" }

aion-event-processor = { path = "../aion-event-processor", optional = true }

[features]
default = ["load-access-builders"]
pipeline-resources = []
load-access-builders = ["aion-event-processor", "pipeline-resources"]